document.addEventListener('DOMContentLoaded', async () => {
  const statusEl = document.getElementById('status');
  const videoInfoEl = document.getElementById('video-info');
  const videoTitleEl = document.getElementById('video-title');
  const captionLanguageEl = document.getElementById('caption-language');
  const trackSelectorEl = document.getElementById('track-selector');
  const tracksSelect = document.getElementById('tracks');
  const captionsContainer = document.getElementById('captions-container');
  const captionsEl = document.getElementById('captions');
  const copyBtn = document.getElementById('copy-btn');
  const errorEl = document.getElementById('error');
  const notYoutubeEl = document.getElementById('not-youtube');
  const showTimecodesCheckbox = document.getElementById('show-timecodes');
  const sendClaudeBtn = document.getElementById('send-claude-btn');
  const claudePromptEl = document.getElementById('claude-prompt');

  let availableTracks = [];
  let currentCaptions = '';
  let currentCaptionsWithTimecodes = '';

  // Load saved Claude prompt
  const savedPrompt = await chrome.storage.local.get(['claudePrompt']);
  if (savedPrompt.claudePrompt) {
    claudePromptEl.value = savedPrompt.claudePrompt;
  }

  // Save Claude prompt on change
  claudePromptEl.addEventListener('change', () => {
    chrome.storage.local.set({ claudePrompt: claudePromptEl.value });
  });

  // Get current tab
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

  // Check if we're on YouTube
  if (!tab.url || !tab.url.includes('youtube.com/watch')) {
    statusEl.classList.add('hidden');
    notYoutubeEl.classList.remove('hidden');
    return;
  }

  // Show loading status
  statusEl.textContent = 'Chargement des sous-titres';
  statusEl.classList.add('loading');

  try {
    // Request captions from content script
    const response = await chrome.tabs.sendMessage(tab.id, { action: 'getCaptions' });

    statusEl.classList.add('hidden');

    if (!response.success) {
      let errorHtml = `<strong>${response.error}</strong>`;

      // Add debug info if available
      if (response.debug) {
        const debugInfo = [];
        if (response.debug.reason) debugInfo.push(`Raison: ${response.debug.reason}`);
        if (response.debug.playabilityStatus) debugInfo.push(`Statut: ${response.debug.playabilityStatus}`);
        if (response.debug.jsonStatus) debugInfo.push(`HTTP JSON: ${response.debug.jsonStatus}`);
        if (response.debug.xmlStatus) debugInfo.push(`HTTP XML: ${response.debug.xmlStatus}`);
        if (response.debug.jsonError) debugInfo.push(`Erreur JSON: ${response.debug.jsonError}`);
        if (response.debug.xmlError) debugInfo.push(`Erreur XML: ${response.debug.xmlError}`);
        if (response.debug.jsonLength !== undefined) debugInfo.push(`Taille JSON: ${response.debug.jsonLength} chars`);
        if (response.debug.xmlLength !== undefined) debugInfo.push(`Taille XML: ${response.debug.xmlLength} chars`);
        if (response.debug.source) debugInfo.push(`Source: ${response.debug.source}`);
        if (response.debug.baseUrl) debugInfo.push(`URL: ${response.debug.baseUrl}`);

        if (debugInfo.length > 0) {
          errorHtml += `<div class="debug-info">${debugInfo.join('<br>')}</div>`;
        }

        // Add response preview if available
        if (response.debug.jsonPreview || response.debug.xmlPreview) {
          const preview = response.debug.xmlPreview || response.debug.jsonPreview;
          const escapedPreview = preview
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
          errorHtml += `<div class="response-preview"><strong>Aperçu réponse:</strong><pre>${escapedPreview}</pre></div>`;
        }
      }

      errorEl.innerHTML = errorHtml;
      errorEl.classList.remove('hidden');
      console.log('Debug info:', response.debug);
      return;
    }

    // Show video info
    videoTitleEl.textContent = response.title;

    let languageText = response.language;
    if (response.isAutoGenerated) {
      languageText += ' <span class="auto">(auto-généré)</span>';
    }
    captionLanguageEl.innerHTML = languageText;

    videoInfoEl.classList.remove('hidden');

    // Populate track selector if multiple tracks available
    if (response.availableTracks && response.availableTracks.length > 1) {
      availableTracks = response.availableTracks;
      tracksSelect.innerHTML = '';

      availableTracks.forEach((track, index) => {
        const option = document.createElement('option');
        option.value = index;
        option.textContent = track.name + (track.isAutoGenerated ? ' (auto)' : '');
        tracksSelect.appendChild(option);
      });

      trackSelectorEl.classList.remove('hidden');
    }

    // Store both versions of captions
    currentCaptions = response.captions;
    currentCaptionsWithTimecodes = response.captionsWithTimecodes || response.captions;

    // Show captions (default: without timecodes)
    captionsEl.value = currentCaptions;
    captionsContainer.classList.remove('hidden');

    // Handle timecode toggle
    showTimecodesCheckbox.addEventListener('change', () => {
      if (showTimecodesCheckbox.checked) {
        captionsEl.value = currentCaptionsWithTimecodes;
      } else {
        captionsEl.value = currentCaptions;
      }
    });

  } catch (error) {
    statusEl.classList.add('hidden');

    let errorMessage = 'Erreur de communication avec la page.';
    let debugInfo = error.message || error.toString();

    if (error.message?.includes('Receiving end does not exist')) {
      errorMessage = 'Le script n\'est pas chargé sur cette page.';
      debugInfo = 'Rechargez la page YouTube (Ctrl+R ou Cmd+R) puis réessayez.';
    } else if (error.message?.includes('Could not establish connection')) {
      errorMessage = 'Impossible de se connecter à la page.';
      debugInfo = 'Rechargez la page YouTube puis réessayez.';
    }

    errorEl.innerHTML = `<strong>${errorMessage}</strong><div class="debug-info">${debugInfo}</div>`;
    errorEl.classList.remove('hidden');
    console.error('Error:', error);
  }

  // Handle track selection change
  tracksSelect.addEventListener('change', async () => {
    const selectedTrack = availableTracks[tracksSelect.value];

    captionsEl.value = 'Chargement...';

    try {
      const response = await chrome.tabs.sendMessage(tab.id, {
        action: 'getCaptionsForTrack',
        url: selectedTrack.url
      });

      if (response.success) {
        captionsEl.value = response.captions;

        let languageText = selectedTrack.name;
        if (selectedTrack.isAutoGenerated) {
          languageText += ' <span class="auto">(auto-généré)</span>';
        }
        captionLanguageEl.innerHTML = languageText;
      } else {
        captionsEl.value = 'Erreur: ' + response.error;
      }
    } catch (error) {
      captionsEl.value = 'Erreur lors du chargement';
      console.error('Error:', error);
    }
  });

  // Handle copy button
  copyBtn.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(captionsEl.value);
      copyBtn.textContent = 'Copié !';
      copyBtn.classList.add('copied');

      setTimeout(() => {
        copyBtn.textContent = 'Copier';
        copyBtn.classList.remove('copied');
      }, 2000);
    } catch (error) {
      // Fallback for older browsers
      captionsEl.select();
      document.execCommand('copy');
      copyBtn.textContent = 'Copié !';
      copyBtn.classList.add('copied');

      setTimeout(() => {
        copyBtn.textContent = 'Copier';
        copyBtn.classList.remove('copied');
      }, 2000);
    }
  });

  // Handle send to Claude button
  sendClaudeBtn.addEventListener('click', async () => {
    const prompt = claudePromptEl.value.trim();
    const captions = captionsEl.value;

    if (!captions) {
      return;
    }

    // Build the message
    const message = `${prompt}\n\n---\n\n${captions}`;

    // Save the message to storage for the Claude content script to pick up
    await chrome.storage.local.set({ pendingClaudeMessage: message });

    // Open Claude.ai in a new tab
    chrome.tabs.create({ url: 'https://claude.ai/new' });
  });
});
