import { Router, Request, Response } from 'express';
import { getX10ById, removeVideoFromX10, updateX10Title, updateX10PrePrompt } from '../services/x10.js';
import { getUserSettings, getDefaultPrePromptText } from '../services/settings.js';
import { config } from '../config.js';

export const x10Router = Router();

// CORS middleware for .md endpoints (needed for extension "Copy MD Content")
x10Router.use('/*.md', (req: Request, res: Response, next) => {
  const origin = req.headers.origin;
  if (origin) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  }
  next();
});

// X10 page (Markdown for LLM) - Must be before /:id to match first
x10Router.get('/:id.md', (req: Request, res: Response) => {
  const id = req.params.id;
  const x10 = getX10ById(id);

  if (!x10) {
    return res.status(404).send('# Not found\n\nThis x10 does not exist.');
  }

  // Get user settings for default pre-prompt
  const anonymousId = req.anonymousId;
  const settings = getUserSettings(anonymousId);
  const defaultPrePrompt = getDefaultPrePromptText();
  const effectivePrePrompt = x10.pre_prompt || settings.default_pre_prompt || defaultPrePrompt;

  // Build markdown content
  let md = '';

  // Pre-prompt
  if (effectivePrePrompt) {
    md += `${effectivePrePrompt}\n\n`;
  }

  md += `# ${x10.title || 'Untitled'}\n\n`;

  // Items list
  md += `## Items included\n\n`;
  x10.videos.forEach((item, index) => {
    const isYouTube = item.type === 'youtube' || item.youtube_id;
    const typeLabel = isYouTube ? 'YouTube' : 'Web';
    const durationPart = item.duration ? ` — ${item.duration}` : '';
    md += `${index + 1}. [${typeLabel}] ${item.title} — ${item.channel}${durationPart}\n`;
  });

  md += `\n---\n\n`;

  // Content
  const baseUrl = config.baseUrl;
  md += `## Content\n\n`;
  x10.videos.forEach((item, index) => {
    const isYouTube = item.type === 'youtube' || item.youtube_id;
    const itemId = isYouTube ? item.youtube_id : item.id;

    md += `### ${index + 1}. ${item.title}\n\n`;
    md += `**Type**: ${isYouTube ? 'YouTube Video' : 'Web Page'}  \n`;
    md += `**Source**: ${item.channel}  \n`;
    if (item.duration) {
      md += `**Duration**: ${item.duration}  \n`;
    }
    md += `**URL**: ${item.url}  \n`;
    md += `**MD**: ${baseUrl}/s/${id}/v/${itemId}.md\n\n`;
    md += `${item.transcript}\n\n`;
    md += `---\n\n`;
  });

  // Footer
  const date = new Date(x10.created_at).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
  md += `*Generated by ${config.brandName} — ${date}*\n`;

  res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
  res.send(md);
});

// Single item MD - /s/:id/v/:itemId.md (itemId can be youtube_id or item.id)
x10Router.get('/:id/v/:itemId.md', (req: Request, res: Response) => {
  const { id, itemId } = req.params;
  const x10 = getX10ById(id);

  if (!x10) {
    return res.status(404).send('# Not found\n\nThis x10 does not exist.');
  }

  // Find item by youtube_id OR by item id (for web pages)
  const item = x10.videos.find(v => v.youtube_id === itemId || v.id === itemId);
  if (!item) {
    return res.status(404).send(`# Not found\n\nItem ${itemId} does not exist in this x10.`);
  }

  const isYouTube = item.type === 'youtube' || item.youtube_id;

  // Get user settings for default pre-prompt
  const anonymousId = req.anonymousId;
  const settings = getUserSettings(anonymousId);
  const defaultPrePrompt = getDefaultPrePromptText();
  const effectivePrePrompt = x10.pre_prompt || settings.default_pre_prompt || defaultPrePrompt;

  // Build markdown content
  let md = '';

  // Pre-prompt
  if (effectivePrePrompt) {
    md += `${effectivePrePrompt}\n\n`;
  }

  md += `# ${item.title}\n\n`;
  md += `**Type**: ${isYouTube ? 'YouTube Video' : 'Web Page'}  \n`;
  md += `**Source**: ${item.channel}  \n`;
  if (item.duration) {
    md += `**Duration**: ${item.duration}  \n`;
  }
  md += `**URL**: ${item.url}\n\n`;
  md += `---\n\n`;
  md += `## ${isYouTube ? 'Transcript' : 'Content'}\n\n`;
  md += `${item.transcript}\n\n`;

  // Footer
  const date = new Date(x10.created_at).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
  md += `*Generated by ${config.brandName} — ${date}*\n`;

  res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
  res.send(md);
});

// X10 page (HTML)
x10Router.get('/:id', (req: Request, res: Response) => {
  const { id } = req.params;
  const x10 = getX10ById(id);

  if (!x10) {
    return res.status(404).render('error', {
      title: 'Not found',
      message: 'This x10 does not exist'
    });
  }

  // Format token count for display
  const tokenDisplay = x10.tokenCount > 1000
    ? `~${Math.round(x10.tokenCount / 1000)}K tokens`
    : `~${x10.tokenCount} tokens`;

  // Format date
  const createdDate = new Date(x10.created_at).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });

  // Check if current user is owner (by user_id or anonymous_id)
  const anonymousId = req.anonymousId;
  // TODO: Also check user_id when auth is implemented
  const isOwner = x10.anonymous_id === anonymousId;

  // Get user settings for default pre-prompt
  const settings = getUserSettings(anonymousId);
  const defaultPrePrompt = getDefaultPrePromptText();

  // Determine effective pre-prompt (x10's own, or fall back to user's default)
  const effectivePrePrompt = x10.pre_prompt || settings.default_pre_prompt || defaultPrePrompt;

  res.render('x10', {
    title: x10.title || 'Untitled collection',
    x10,
    tokenDisplay,
    createdDate,
    currentUser: null,
    isOwner,
    isOrphan: x10.user_id === null && x10.anonymous_id === null,
    effectivePrePrompt,
    defaultPrePrompt
  });
});

// Helper to check if user can edit x10
function canEdit(x10: ReturnType<typeof getX10ById>, anonymousId: string): boolean {
  if (!x10) return false;
  // Owner by anonymous_id
  if (x10.anonymous_id === anonymousId) return true;
  // TODO: Also check user_id when auth is implemented
  return false;
}

// DISABLED: Server-side extraction removed
// Adding content from the web page is temporarily disabled - use the Chrome extension instead
x10Router.post('/:id/add', (_req: Request, res: Response) => {
  return res.status(410).json({
    error: 'Adding content from the web is temporarily disabled. Please use the Chrome extension.',
    hint: 'Content extraction now happens client-side to avoid rate limiting.'
  });
});

// Remove video from x10
x10Router.post('/:id/remove/:videoId', (req: Request, res: Response) => {
  const { id, videoId } = req.params;

  const x10 = getX10ById(id);
  if (!x10) {
    return res.status(404).json({ error: 'X10 not found' });
  }

  // Check ownership
  if (!canEdit(x10, req.anonymousId)) {
    return res.status(403).json({ error: 'Not authorized to edit this x10' });
  }

  const success = removeVideoFromX10(id, videoId);
  if (success) {
    res.redirect(`/s/${id}`);
  } else {
    res.status(404).json({ error: 'Video not found' });
  }
});

// Update x10 title
x10Router.post('/:id/title', (req: Request, res: Response) => {
  const { id } = req.params;
  const { title } = req.body;

  const x10 = getX10ById(id);
  if (!x10) {
    return res.status(404).json({ error: 'X10 not found' });
  }

  // Check ownership
  if (!canEdit(x10, req.anonymousId)) {
    return res.status(403).json({ error: 'Not authorized to edit this x10' });
  }

  const success = updateX10Title(id, title);
  if (success) {
    res.redirect(`/s/${id}`);
  } else {
    res.status(404).json({ error: 'X10 not found' });
  }
});

// Update x10 pre-prompt
x10Router.post('/:id/preprompt', (req: Request, res: Response) => {
  const { id } = req.params;
  const { prePrompt } = req.body;

  const x10 = getX10ById(id);
  if (!x10) {
    return res.status(404).json({ error: 'X10 not found' });
  }

  // Check ownership
  if (!canEdit(x10, req.anonymousId)) {
    return res.status(403).json({ error: 'Not authorized to edit this x10' });
  }

  const success = updateX10PrePrompt(id, prePrompt || null);
  if (success) {
    res.redirect(`/s/${id}`);
  } else {
    res.status(404).json({ error: 'X10 not found' });
  }
});
