import { Router, Request, Response } from 'express';
import { getX10ById, addVideoToX10, removeVideoFromX10, updateX10Title, updateX10PrePrompt } from '../services/x10.js';
import { extractVideoId } from '../services/transcript.js';
import { getUserSettings, getDefaultPrePromptText } from '../services/settings.js';

export const x10Router = Router();

// X10 page (Markdown for LLM) - Must be before /:id to match first
x10Router.get('/:id.md', (req: Request, res: Response) => {
  const id = req.params.id;
  const x10 = getX10ById(id);

  if (!x10) {
    return res.status(404).send('# Not found\n\nThis x10 does not exist.');
  }

  // Get user settings for default pre-prompt
  const anonymousId = req.anonymousId;
  const settings = getUserSettings(anonymousId);
  const defaultPrePrompt = getDefaultPrePromptText();
  const effectivePrePrompt = x10.pre_prompt || settings.default_pre_prompt || defaultPrePrompt;

  // Build markdown content
  let md = '';

  // Pre-prompt
  if (effectivePrePrompt) {
    md += `${effectivePrePrompt}\n\n`;
  }

  md += `# ${x10.title || 'Untitled'}\n\n`;

  // Videos list
  md += `## Videos included\n\n`;
  x10.videos.forEach((video, index) => {
    md += `${index + 1}. ${video.title} — ${video.channel} — ${video.duration}\n`;
  });

  md += `\n---\n\n`;

  // Transcripts
  md += `## Transcripts\n\n`;
  x10.videos.forEach((video, index) => {
    md += `### ${index + 1}. ${video.title}\n\n`;
    md += `**Channel**: ${video.channel}  \n`;
    md += `**Duration**: ${video.duration}  \n`;
    md += `**URL**: ${video.url}\n\n`;
    md += `${video.transcript}\n\n`;
    md += `---\n\n`;
  });

  // Footer
  const date = new Date(x10.created_at).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
  md += `*Generated by X10Tube — ${date}*\n`;

  res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
  res.send(md);
});

// Single video MD - /s/:id/v/:videoIndex.md (1-based index)
x10Router.get('/:id/v/:videoIndex.md', (req: Request, res: Response) => {
  const { id } = req.params;
  const videoIndex = parseInt(req.params.videoIndex, 10);
  const x10 = getX10ById(id);

  if (!x10) {
    return res.status(404).send('# Not found\n\nThis x10 does not exist.');
  }

  // Validate video index (1-based)
  if (isNaN(videoIndex) || videoIndex < 1 || videoIndex > x10.videos.length) {
    return res.status(404).send(`# Not found\n\nVideo ${videoIndex} does not exist in this x10.`);
  }

  const video = x10.videos[videoIndex - 1];

  // Get user settings for default pre-prompt
  const anonymousId = req.anonymousId;
  const settings = getUserSettings(anonymousId);
  const defaultPrePrompt = getDefaultPrePromptText();
  const effectivePrePrompt = x10.pre_prompt || settings.default_pre_prompt || defaultPrePrompt;

  // Build markdown content
  let md = '';

  // Pre-prompt
  if (effectivePrePrompt) {
    md += `${effectivePrePrompt}\n\n`;
  }

  md += `# ${video.title}\n\n`;
  md += `**Channel**: ${video.channel}  \n`;
  md += `**Duration**: ${video.duration}  \n`;
  md += `**URL**: ${video.url}\n\n`;
  md += `---\n\n`;
  md += `## Transcript\n\n`;
  md += `${video.transcript}\n\n`;

  // Footer
  const date = new Date(x10.created_at).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
  md += `*Generated by X10Tube — ${date}*\n`;

  res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
  res.send(md);
});

// X10 page (HTML)
x10Router.get('/:id', (req: Request, res: Response) => {
  const { id } = req.params;
  const x10 = getX10ById(id);

  if (!x10) {
    return res.status(404).render('error', {
      title: 'Not found',
      message: 'This x10 does not exist'
    });
  }

  // Format token count for display
  const tokenDisplay = x10.tokenCount > 1000
    ? `~${Math.round(x10.tokenCount / 1000)}K tokens`
    : `~${x10.tokenCount} tokens`;

  // Format date
  const createdDate = new Date(x10.created_at).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });

  // Check if current user is owner (by user_id or anonymous_id)
  const anonymousId = req.anonymousId;
  // TODO: Also check user_id when auth is implemented
  const isOwner = x10.anonymous_id === anonymousId;

  // Get user settings for default pre-prompt
  const settings = getUserSettings(anonymousId);
  const defaultPrePrompt = getDefaultPrePromptText();

  // Determine effective pre-prompt (x10's own, or fall back to user's default)
  const effectivePrePrompt = x10.pre_prompt || settings.default_pre_prompt || defaultPrePrompt;

  res.render('x10', {
    title: x10.title || 'Untitled x10',
    x10,
    tokenDisplay,
    createdDate,
    currentUser: null,
    isOwner,
    isOrphan: x10.user_id === null && x10.anonymous_id === null,
    effectivePrePrompt,
    defaultPrePrompt
  });
});

// Helper to check if user can edit x10
function canEdit(x10: ReturnType<typeof getX10ById>, anonymousId: string): boolean {
  if (!x10) return false;
  // Owner by anonymous_id
  if (x10.anonymous_id === anonymousId) return true;
  // TODO: Also check user_id when auth is implemented
  return false;
}

// Add video to x10
x10Router.post('/:id/add', async (req: Request, res: Response) => {
  const { id } = req.params;
  const { url } = req.body;

  const x10 = getX10ById(id);
  if (!x10) {
    return res.status(404).json({ error: 'X10 not found' });
  }

  // Check ownership
  if (!canEdit(x10, req.anonymousId)) {
    return res.status(403).json({ error: 'Not authorized to edit this x10' });
  }

  // Check video limit
  if (x10.videos.length >= 10) {
    return res.status(400).json({ error: 'Maximum 10 videos per x10' });
  }

  // Check if video already exists
  const videoId = extractVideoId(url);
  if (videoId && x10.videos.some(v => v.youtube_id === videoId)) {
    return res.status(400).json({ error: 'This video is already in this x10' });
  }

  try {
    const video = await addVideoToX10(id, url);
    res.redirect(`/s/${id}`);
  } catch (error) {
    res.status(400).json({
      error: error instanceof Error ? error.message : 'Could not add video'
    });
  }
});

// Remove video from x10
x10Router.post('/:id/remove/:videoId', (req: Request, res: Response) => {
  const { id, videoId } = req.params;

  const x10 = getX10ById(id);
  if (!x10) {
    return res.status(404).json({ error: 'X10 not found' });
  }

  // Check ownership
  if (!canEdit(x10, req.anonymousId)) {
    return res.status(403).json({ error: 'Not authorized to edit this x10' });
  }

  const success = removeVideoFromX10(id, videoId);
  if (success) {
    res.redirect(`/s/${id}`);
  } else {
    res.status(404).json({ error: 'Video not found' });
  }
});

// Update x10 title
x10Router.post('/:id/title', (req: Request, res: Response) => {
  const { id } = req.params;
  const { title } = req.body;

  const x10 = getX10ById(id);
  if (!x10) {
    return res.status(404).json({ error: 'X10 not found' });
  }

  // Check ownership
  if (!canEdit(x10, req.anonymousId)) {
    return res.status(403).json({ error: 'Not authorized to edit this x10' });
  }

  const success = updateX10Title(id, title);
  if (success) {
    res.redirect(`/s/${id}`);
  } else {
    res.status(404).json({ error: 'X10 not found' });
  }
});

// Update x10 pre-prompt
x10Router.post('/:id/preprompt', (req: Request, res: Response) => {
  const { id } = req.params;
  const { prePrompt } = req.body;

  const x10 = getX10ById(id);
  if (!x10) {
    return res.status(404).json({ error: 'X10 not found' });
  }

  // Check ownership
  if (!canEdit(x10, req.anonymousId)) {
    return res.status(403).json({ error: 'Not authorized to edit this x10' });
  }

  const success = updateX10PrePrompt(id, prePrompt || null);
  if (success) {
    res.redirect(`/s/${id}`);
  } else {
    res.status(404).json({ error: 'X10 not found' });
  }
});
