#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
EXT_SRC="$PROJECT_DIR/extension"
DIST_DIR="$PROJECT_DIR/dist-extension"
ENV_FILE="$PROJECT_DIR/.env"

# Load URLs from the single root .env file
if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found"
  exit 1
fi

source "$ENV_FILE"

if [ -z "$DEV_URL" ] || [ -z "$PROD_URL" ]; then
  echo "Error: DEV_URL and PROD_URL must be set in $ENV_FILE"
  exit 1
fi

echo "DEV_URL  = $DEV_URL"
echo "PROD_URL = $PROD_URL"
echo ""

rm -rf "$DIST_DIR"

for ENV in dev prod; do
  echo "Building $ENV extension..."
  mkdir -p "$DIST_DIR/$ENV"

  # Copy all extension files
  cp -r "$EXT_SRC"/* "$DIST_DIR/$ENV/"

  # Remove markdown docs from the build
  rm -f "$DIST_DIR/$ENV/"*.md

  # Pick the right URL
  if [ "$ENV" = "prod" ]; then
    URL="$PROD_URL"
  else
    URL="$DEV_URL"
  fi

  # Generate config.js with the correct URL
  cat > "$DIST_DIR/$ENV/config.js" <<CONFIGEOF
// Generated by build-extension.sh — do not edit manually
// Environment: $ENV
const STYA_CONFIG = {
  DEFAULT_BASE_URL: '$URL',
};
CONFIGEOF

  echo "  -> $DIST_DIR/$ENV/ (URL: $URL)"
done

echo ""
echo "Done! Load in Chrome:"
echo "  Dev:  chrome://extensions -> Load unpacked -> dist-extension/dev"
echo "  Prod: chrome://extensions -> Load unpacked -> dist-extension/prod"
